### ISSUE TITLE
reqContractDetails is broken

### ISSUE THREAD

**Issue by eyalk11** [ib-api-reloaded/ib_async#27]
It returns timeout or doesn't return. 

minimal example: 
```
from ib_async import IB
ib=IB()
ib.connect(port=7596)
from ib_async import Contract
contract= Contract()
contract.conId=416843
ib.reqContractDetails(contract)
```

Same commands different context: 

```
2024-06-07 20:06:09,900 ib_async.client DEBUG >>> 9,8,1,416843,,,,0.0,,,,,,,,0,,,
Traceback (most recent call last):
  File "C:\Users\ekarni\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 458, in wait_for
    fut.result()
asyncio.exceptions.CancelledError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\Users\ekarni\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\runner.py", line 339, in from_call
    result: Optional[TResult] = func()
  File "C:\Users\ekarni\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\runner.py", line 260, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "C:\Users\ekarni\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\ekarni\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\ekarni\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "C:\Users\ekarni\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Users\ekarni\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\ekarni\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\runner.py", line 175, in pytest_runtest_call
    raise e
  File "C:\Users\ekarni\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\runner.py", line 167, in pytest_runtest_call
    item.runtest()
  File "C:\Users\ekarni\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\python.py", line 1789, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\Users\ekarni\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\ekarni\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\ekarni\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "C:\Users\ekarni\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Users\ekarni\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\ekarni\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\python.py", line 195, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "C:\Users\ekarni\compare-my-stocks\src\compare_my_stocks\tests\test_it.py", line 119, in test_get_currentcurrency
    zz = tmpinp._inputsource.ibrem.ib.reqContractDetails(contract)
  File "c:\gitproj\ib_insync\ib_async\ib.py", line 1042, in reqContractDetails
    return self._run(self.reqContractDetailsAsync(contract))
  File "c:\gitproj\ib_insync\ib_async\ib.py", line 381, in _run
    return util.run(*awaitables, timeout=self.RequestTimeout)
  File "c:\gitproj\ib_insync\ib_async\util.py", line 357, in run
    result = loop.run_until_complete(task)
  File "C:\Users\ekarni\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\ekarni\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 460, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

```

**Comment by gnzsnz** [comment]
i'm using it on a daily basis on multiple contracts without any issue

the traceback that you are showing is for pytest not for ib_async. check your tests

**Comment by eyalk11** [comment]
I know that  I showed the exception from another context. 
But the code above as it is hanged for me in python 3.10 .

**Comment by eyalk11** [comment]
My mistake. Apparently IB client is somehow broken in a way that it returns timeout on some reqs but not others in certain situations . The same code worked later.
